# Generated by Django 5.2 on 2025-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_no',
            field=models.CharField(default='00000', max_length=255),
            preserve_default=False,
        ),
    ]
